import type { User } from '@40labs/types';
import { WORKSPACE_ID, BRANCH_ID, daysAgoIso } from '../constants';

export const initialUsers: User[] = [
  {
    id: 'user_001',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(90),
    updated_at: daysAgoIso(90),
    username: 'sairiamu',
    first_name: 'Sairiamu',
    last_name: 'Mwakalinga',
    full_name: 'Sairiamu Mwakalinga',
    phone: '+255 715 000 111',
    role: 'sudo',
    role_preset: 'sudo',
    is_superintendent: true,
    active: true,
    owner_id: 'owner_001',
    must_change_credentials: false,
    last_login_at: daysAgoIso(1),
    created_by_user_id: null,
    pin_hash: 'mock_hash_sudo',
    permissions: null,
    contacts: '+255 715 000 111',
    location: 'Main Branch - Dar es Salaam',
  },
  {
    id: 'user_002',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(60),
    updated_at: daysAgoIso(10),
    username: 'gmushi',
    first_name: 'Grace',
    last_name: 'Mushi',
    full_name: 'Grace Mushi',
    phone: '+255 784 123 456',
    role: 'staff',
    role_preset: 'pharmacist',
    is_superintendent: false,
    active: true,
    owner_id: 'owner_001',
    must_change_credentials: false,
    last_login_at: daysAgoIso(2),
    created_by_user_id: 'user_001',
    pin_hash: 'mock_hash_staff_1',
    permissions: {
      can_update_stock: true,
      can_adjust_stock: false,
      can_issue_refund: false,
      can_approve_po: false,
      can_add_lab_sample: true,
      can_override_lab_result: false,
      can_view_reports: true,
    },
    contacts: '+255 784 123 456',
    location: 'Main Branch - Dar es Salaam',
  },
  {
    id: 'user_003',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(45),
    updated_at: daysAgoIso(45),
    username: 'ekileo',
    first_name: 'Emmanuel',
    last_name: 'Kileo',
    full_name: 'Emmanuel Kileo',
    phone: '+255 655 987 654',
    role: 'staff',
    role_preset: 'lab_technician',
    is_superintendent: false,
    active: true,
    owner_id: 'owner_001',
    must_change_credentials: false,
    last_login_at: daysAgoIso(5),
    created_by_user_id: 'user_001',
    pin_hash: 'mock_hash_staff_2',
    permissions: {
      can_update_stock: true,
      can_adjust_stock: true,
      can_issue_refund: false,
      can_approve_po: false,
      can_add_lab_sample: false,
      can_override_lab_result: false,
      can_view_reports: false,
    },
    contacts: '+255 655 987 654',
    location: 'Posta Branch',
  },
];
