// Tailwind v4 bridge for the dark 40Labs desktop theme.
const { colors, radius, fonts, spacing, elevation } = require('./index.ts');

module.exports = {
  colors: {
    'app-bg': colors.appBg,
    'top-chrome': colors.topChrome,
    sidebar: colors.sidebar,
    'surface-primary': colors.surfacePrimary,
    'surface-secondary': colors.surfaceSecondary,
    'surface-elevated': colors.surfaceElevated,
    'surface-hover': colors.surfaceHover,
    'surface-active': colors.surfaceActive,
    'surface-selected': colors.surfaceSelected,
    'surface-disabled': colors.surfaceDisabled,
    'border-subtle': colors.borderSubtle,
    'border-default': colors.borderDefault,
    'border-strong': colors.borderStrong,
    'border-focus': colors.borderFocus,
    'border-selected': colors.borderSelected,
    divider: colors.divider,
    'text-primary': colors.textPrimary,
    'text-secondary': colors.textSecondary,
    'text-muted': colors.textMuted,
    'text-disabled': colors.textDisabled,
    'action-primary': colors.actionPrimary,
    'action-primary-hover': colors.actionPrimaryHover,
    'action-primary-active': colors.actionPrimaryActive,
    success: colors.success,
    'success-bg': colors.successBg,
    'success-border': colors.successBorder,
    warning: colors.warning,
    'warning-bg': colors.warningBg,
    'warning-border': colors.warningBorder,
    danger: colors.danger,
    'danger-bg': colors.dangerBg,
    'danger-border': colors.dangerBorder,
    info: colors.info,
    'info-bg': colors.infoBg,
    'info-border': colors.infoBorder,
    'focus-ring': colors.focusRing,

    // Legacy aliases
    primary: colors.primary,
    accent: colors.accent,
    surface: colors.surface,
    'surface-strong': colors.surfaceStrong,
    panel: colors.panel,
    'panel-strong': colors.panelStrong,
    input: colors.input,
    field: colors.field,
    text: colors.text,
    border: colors.border,
  },
  borderRadius: {
    none: radius.none,
    xs: radius.xs,
    sm: radius.sm,
    md: radius.md,
    lg: radius.lg,
    card: radius.card,
    input: radius.input,
    full: radius.full,
  },
  boxShadow: elevation,
  fontFamily: {
    heading: [fonts.heading, 'sans-serif'],
    ui: [fonts.ui, 'sans-serif'],
    mono: [fonts.mono, 'monospace'],
  },
};
