import React,{useMemo,useState} from 'react';
import {Card} from '@40labs/ui-components';
import {useInventoryList} from '../inventory/useInventory';
import {useCustomerList,useCustomer,useCreateCustomer} from '../customers/useCustomers';
import {useSaleCart} from './useSales';
import {SaleCartTable} from './SaleCartTable';
import {SaleSummaryPanel} from './SaleSummaryPanel';
import type {Customer} from '@40labs/types';

export default function SalesScreen(){
 const{data:inventory=[],isLoading}=useInventoryList();const{data:customers=[]}=useCustomerList();const{lines,customer_id,addLine,setCustomer}=useSaleCart();
 const[customerName,setCustomerName]=useState('');const[customerContact,setCustomerContact]=useState('');const[selected,setSelected]=useState<Customer|null>(null);const[draft,setDraft]=useState<{full_name:string;phone:string}|null>(null);const[medicineSearch,setMedicineSearch]=useState('');const createCustomer=useCreateCustomer();const{data:persisted}=useCustomer(customer_id);const customer=selected??persisted??null;
 const matches=useMemo(()=>{const q=`${customerName} ${customerContact}`.trim().toLowerCase();if(!q)return[];return customers.filter(c=>c.full_name.toLowerCase().includes(q)||c.phone.toLowerCase().includes(q)||(c.email??'').toLowerCase().includes(q));},[customers,customerName,customerContact]);
 const filteredInventory=useMemo(()=>{const q=medicineSearch.trim().toLowerCase();if(!q)return inventory;return inventory.filter(i=>i.medicine.name.toLowerCase().includes(q)||i.medicine.generic_name.toLowerCase().includes(q)||i.batch_number.toLowerCase().includes(q));},[inventory,medicineSearch]);
 const selectCustomer=(c:Customer)=>{setSelected(c);setDraft(null);setCustomerName(c.full_name);setCustomerContact(c.phone);setCustomer(c.id)};
 const changeCustomer=()=>{setSelected(null);setDraft(null);setCustomer(null);setCustomerName('');setCustomerContact('')};
 const updateName=(v:string)=>{setSelected(null);setCustomer(null);setCustomerName(v);setDraft({full_name:v,phone:customerContact})};const updateContact=(v:string)=>{setSelected(null);setCustomer(null);setCustomerContact(v);setDraft({full_name:customerName,phone:v})};
 const complete=async()=>{if(customer_id)return true;if(!draft?.full_name.trim()&&!draft?.phone.trim())return true;if(!draft?.full_name.trim()||!draft.phone.trim()){alert('Enter both customer name and phone, or continue as walk-in.');return false;}const c=await createCustomer.mutateAsync({full_name:draft.full_name.trim(),phone:draft.phone.trim(),email:null});selectCustomer(c);return true};
 return <div className="h-full bg-surface text-text p-3 flex flex-col gap-2 overflow-hidden">
  <header className="h-10 shrink-0 flex items-center gap-3 px-1"><div className="w-8 h-8 rounded-full bg-primary elevation-raised"/><h1 className="font-heading text-sm font-bold text-accent">Sales</h1></header>
  <div className="grid min-h-0 flex-1 grid-cols-[minmax(205px,24%)_minmax(360px,1fr)_minmax(230px,27%)] gap-1.5">
   <aside className="min-h-0 overflow-hidden rounded-card bg-panel p-2 elevation-raised flex flex-col">
    <div className="shrink-0 space-y-2"><input value={customerName} onChange={e=>updateName(e.target.value)} placeholder="Customer’s name" className="h-8 w-full rounded-input bg-input px-3 text-xs text-text placeholder:text-text-muted elevation-inset focus:outline-none"/><input value={customerContact} onChange={e=>updateContact(e.target.value)} placeholder="Customer’s phone/email" className="h-8 w-full rounded-input bg-input px-3 text-xs text-text placeholder:text-text-muted elevation-inset focus:outline-none"/>{!customer&&!draft?.full_name&&!draft?.phone&&<p className="text-[9px] text-text-muted px-1">Search existing customer first. A new buyer can continue without registration.</p>}{!customer&&matches.length>0&&<div className="space-y-1">{matches.slice(0,3).map(c=><button key={c.id} onClick={()=>selectCustomer(c)} className="w-full rounded-input bg-panel-strong p-2 text-left elevation-raised"><p className="text-xs text-text">{c.full_name}</p><p className="text-[9px] font-mono text-text-muted">{c.phone}</p></button>)}</div>}</div>
    <div className="min-h-0 flex-1 mt-2 rounded-card bg-field text-[#252525] p-3 overflow-y-auto">{customer?<><p className="text-sm font-semibold">{customer.full_name}</p><p className="mt-4 text-xs">phone</p><p className="text-xs font-mono">{customer.phone}</p>{customer.email&&<><p className="mt-3 text-xs">email</p><p className="text-xs">{customer.email}</p></>}<p className="mt-5 text-xs">Service</p><p className="mt-1 text-xs">Sales / Pharmacy</p><p className="mt-5 text-xs">Outstanding</p><p className="text-sm font-mono">TZS {customer.outstanding_balance.toLocaleString()}</p></>:<><p className="text-xs font-semibold">pharmacy name</p><p className="mt-5 text-xs">name</p><p className="mt-2 text-xs">phone</p><p className="mt-2 text-xs">email</p><p className="mt-5 text-xs">Service</p><p className="mt-1 text-xs">cost</p><p className="mt-5 text-xs">Description</p>{draft?.full_name&&<p className="mt-5 text-xs font-semibold">{draft.full_name}</p>}{draft?.phone&&<p className="mt-1 text-xs font-mono">{draft.phone}</p>}</>}</div>
    <div className="mt-2 shrink-0 flex gap-1.5"><button onClick={changeCustomer} className="h-8 flex-1 rounded-input bg-panel-strong text-text-muted text-[10px] elevation-raised">{customer?'Change':'Walk-in'}</button><button onClick={()=>draft?.full_name&&draft.phone&&complete()} className="h-8 flex-[1.5] rounded-input bg-panel-strong text-text-muted text-[10px] elevation-raised">Send Report To Customer</button></div>
   </aside>
   <section className="min-h-0 flex flex-col rounded-card bg-panel elevation-raised overflow-hidden"><div className="h-10 shrink-0 px-3 flex items-center justify-between border-b border-border"><span className="font-heading text-sm font-semibold text-text">Cart</span><span className="rounded-full bg-primary px-2 py-1 text-[9px] text-surface font-semibold">{lines.length} ITEMS</span></div><div className="min-h-0 flex-1 overflow-y-auto p-2"><SaleCartTable/></div><SaleSummaryPanel onCompleteSale={complete} completingSale={createCustomer.isPending}/></section>
   <aside className="min-h-0 rounded-card bg-panel elevation-raised p-2 flex flex-col overflow-hidden"><input value={medicineSearch} onChange={e=>setMedicineSearch(e.target.value)} placeholder="Search medicine..." className="h-8 shrink-0 w-full rounded-input bg-input px-3 text-xs text-text placeholder:text-text-muted elevation-inset focus:outline-none"/><button className="mt-2 h-8 shrink-0 rounded-full bg-primary elevation-raised" aria-label="Search medicine"/><div className="min-h-0 flex-1 overflow-y-auto mt-2 space-y-2">{isLoading?<p className="p-4 text-xs text-text-muted">Loading...</p>:filteredInventory.map(item=><Card key={item.id} interactive className="p-3 bg-panel-strong" onClick={()=>addLine(item.id,1)}><div className="flex justify-between gap-2"><div className="min-w-0"><p className="truncate text-xs font-semibold text-text">{item.medicine.name}</p><p className="truncate text-[9px] text-text-muted italic">{item.medicine.generic_name}</p></div><span className="font-mono text-[9px] text-text-muted">{item.quantity}</span></div><div className="mt-2 pt-2 border-t border-border flex justify-between"><span className="font-mono text-[9px] text-text-muted">Batch: {item.batch_number}</span><span className="font-mono text-xs font-bold text-primary">{item.sell_price.toLocaleString()}</span></div></Card>)}</div></aside>
  </div>
 </div>;
}
