import type { Medicine } from '@40labs/types';
import { WORKSPACE_ID, BRANCH_ID, daysAgoIso } from '../constants';

export const initialMedicines: Medicine[] = [
  {
    id: 'med_001',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(200),
    updated_at: daysAgoIso(200),
    name: 'Paracetamol 500mg',
    generic_name: 'Paracetamol',
    category: 'Analgesic',
    unit: 'pack',
    is_controlled_substance: false,
    requires_prescription: false,
  },
  {
    id: 'med_002',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(200),
    updated_at: daysAgoIso(200),
    name: 'Amoxicillin 250mg',
    generic_name: 'Amoxicillin',
    category: 'Antibiotic',
    unit: 'pack',
    is_controlled_substance: false,
    requires_prescription: true,
  },
  {
    id: 'med_003',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(150),
    updated_at: daysAgoIso(150),
    name: 'Diazepam 5mg',
    generic_name: 'Diazepam',
    category: 'Sedative',
    unit: 'pack',
    is_controlled_substance: true,
    requires_prescription: true,
  },
  {
    id: 'med_004',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(100),
    updated_at: daysAgoIso(100),
    name: 'ORS Sachets',
    generic_name: 'Oral Rehydration Salts',
    category: 'Rehydration',
    unit: 'sachet',
    is_controlled_substance: false,
    requires_prescription: false,
  },
];
