import type { InventoryItem, StockAdjustment } from '@40labs/types';
import { WORKSPACE_ID, BRANCH_ID, daysAgoIso, daysFromNowIso } from '../constants';

export const initialInventoryItems: InventoryItem[] = [
  {
    id: 'inv_001',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(60),
    updated_at: daysAgoIso(2),
    medicine_id: 'med_001',
    batch_number: 'PCM-2026-014',
    expiry_date: daysFromNowIso(400),
    buy_price: 2000,
    sell_price: 3000,
    quantity: 240,
    low_stock_threshold: 50,
    cold_chain_required: false,
  },
  {
    id: 'inv_002',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(40),
    updated_at: daysAgoIso(5),
    medicine_id: 'med_002',
    batch_number: 'AMX-2026-009',
    expiry_date: daysFromNowIso(30),
    buy_price: 3500,
    sell_price: 5000,
    quantity: 18,
    low_stock_threshold: 20,
    cold_chain_required: false,
  },
  {
    id: 'inv_003',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(20),
    updated_at: daysAgoIso(20),
    medicine_id: 'med_003',
    batch_number: 'DZP-2026-002',
    expiry_date: daysFromNowIso(200),
    buy_price: 8000,
    sell_price: 12000,
    quantity: 15,
    low_stock_threshold: 5,
    cold_chain_required: false,
  },
  {
    id: 'inv_004',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(15),
    updated_at: daysAgoIso(15),
    medicine_id: 'med_004',
    batch_number: 'ORS-2025-088',
    expiry_date: daysAgoIso(3),
    buy_price: 300,
    sell_price: 500,
    quantity: 60,
    low_stock_threshold: 30,
    cold_chain_required: false,
  },
];

export const initialStockAdjustments: StockAdjustment[] = [
  {
    id: 'adj_001',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(2),
    updated_at: daysAgoIso(2),
    inventory_item_id: 'inv_001',
    adjusted_by_user_id: 'user_003',
    delta: -5,
    reason: 'Damaged in storage',
    audit_log_id: 'audit_001',
  },
];
