import type { Schedule } from '@40labs/types';
import { WORKSPACE_ID, BRANCH_ID, nowIso, daysFromNowIso, daysAgoIso } from '../constants';

export const mockSchedules: Schedule[] = [
  {
    id: 'sch_001',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    title: 'Monthly TMDA Compliance Report',
    category: 'gov',
    schedule_type: 'report',
    channels: ['google_drive', 'gmail'],
    recipient_scope: 'custom',
    recipient_ids: ['gov_tmda_01'],
    message_body: 'Automated monthly dispensing and controlled substance registry report for TMDA submission.',
    attachments: ['tmda_report_aug_2026.pdf'],
    scheduled_at: daysFromNowIso(1),
    repeat_interval: 'monthly',
    repeat_until: daysFromNowIso(365),
    status: 'pending',
    sent_count: 5,
    pending_count: 1,
    failure_count: 0,
    created_at: daysAgoIso(30),
    updated_at: daysAgoIso(1),
  },
  {
    id: 'sch_002',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    title: 'Chronic Refill Reminder - Metformin & Amlodipine',
    category: 'patients',
    schedule_type: 'refill',
    channels: ['whatsapp', 'sms'],
    recipient_scope: 'subscribers',
    recipient_ids: null,
    message_body: 'Jambo! Your monthly refill for chronic medication is due in 3 days. Visit 40Labs Afya Pharmacy or reply to order delivery.',
    attachments: null,
    scheduled_at: nowIso(),
    repeat_interval: 'weekly',
    repeat_until: daysFromNowIso(90),
    status: 'pending',
    sent_count: 24,
    pending_count: 12,
    failure_count: 2,
    created_at: daysAgoIso(14),
    updated_at: nowIso(),
  },
  {
    id: 'sch_003',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    title: 'Daily Sales & Revenue Summary',
    category: 'reports',
    schedule_type: 'report',
    channels: ['gmail', 'google_drive'],
    recipient_scope: 'staff',
    recipient_ids: ['user_001', 'user_002'],
    message_body: 'End of day sales reconciliation report generated automatically by 40Labs Core.',
    attachments: ['daily_sales_summary.pdf'],
    scheduled_at: daysAgoIso(1),
    repeat_interval: 'daily',
    repeat_until: null,
    status: 'sent',
    sent_count: 45,
    pending_count: 0,
    failure_count: 0,
    created_at: daysAgoIso(45),
    updated_at: daysAgoIso(1),
  },
  {
    id: 'sch_004',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    title: 'Malaria Awareness & Testing Campaign',
    category: 'marketing',
    schedule_type: 'broadcast',
    channels: ['sms', 'whatsapp'],
    recipient_scope: 'customers',
    recipient_ids: null,
    message_body: 'Protect your family this rainy season. Walk into 40Labs Pharmacy for rapid malaria screening and consultation.',
    attachments: null,
    scheduled_at: daysAgoIso(2),
    repeat_interval: 'none',
    repeat_until: null,
    status: 'failed',
    sent_count: 120,
    pending_count: 0,
    failure_count: 35,
    created_at: daysAgoIso(3),
    updated_at: daysAgoIso(2),
  },
  {
    id: 'sch_005',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    title: 'Staff Shift Handover & Inventory Check',
    category: 'reports',
    schedule_type: 'reminder',
    channels: ['in_app'],
    recipient_scope: 'staff',
    recipient_ids: ['user_001', 'user_002', 'user_003'],
    message_body: 'Reminder to complete controlled substance count and shift handover log.',
    attachments: null,
    scheduled_at: daysFromNowIso(2),
    repeat_interval: 'daily',
    repeat_until: daysFromNowIso(180),
    status: 'pending',
    sent_count: 12,
    pending_count: 1,
    failure_count: 0,
    created_at: daysAgoIso(10),
    updated_at: daysAgoIso(1),
  },
  {
    id: 'sch_006',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    title: 'Quarterly NHIF Claims Submission',
    category: 'gov',
    schedule_type: 'report',
    channels: ['gmail'],
    recipient_scope: 'custom',
    recipient_ids: ['nhif_portal_01'],
    message_body: 'Quarterly accredited dispensary insurance claims and patient dispensing verification bundle.',
    attachments: ['nhif_claims_q3.zip'],
    scheduled_at: daysAgoIso(10),
    repeat_interval: 'monthly',
    repeat_until: null,
    status: 'sent',
    sent_count: 3,
    pending_count: 0,
    failure_count: 0,
    created_at: daysAgoIso(90),
    updated_at: daysAgoIso(10),
  },
  {
    id: 'sch_007',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    title: 'Vitamin & Supplement Promo Broadcast',
    category: 'marketing',
    schedule_type: 'broadcast',
    channels: ['whatsapp'],
    recipient_scope: 'customers',
    recipient_ids: null,
    message_body: 'Special 15% discount on all multivitamins and immune boosters this weekend at 40Labs Pharmacy.',
    attachments: null,
    scheduled_at: daysFromNowIso(5),
    repeat_interval: 'none',
    repeat_until: null,
    status: 'cancelled',
    sent_count: 0,
    pending_count: 0,
    failure_count: 0,
    created_at: daysAgoIso(5),
    updated_at: daysAgoIso(4),
  },
];
