import type { LabOrder } from '@40labs/types';
import { WORKSPACE_ID, BRANCH_ID, daysAgoIso, nowIso } from '../constants';

export const initialLabOrders: LabOrder[] = [
  {
    id: 'labord_001',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(2),
    updated_at: daysAgoIso(1),
    customer_id: 'cust_001',
    sale_id: null,
    ordered_by_user_id: 'user_001',
    status: 'report_ready',
    test_catalog_id: 'test_001',
  },
  {
    id: 'labord_002',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(1),
    updated_at: daysAgoIso(1),
    customer_id: 'cust_002',
    sale_id: 'sale_002',
    ordered_by_user_id: 'user_002',
    status: 'sample_collected',
    test_catalog_id: 'test_002',
  },
  {
    id: 'labord_003',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: nowIso(),
    updated_at: nowIso(),
    customer_id: 'cust_003',
    sale_id: null,
    ordered_by_user_id: 'user_001',
    status: 'pending',
    test_catalog_id: 'test_003',
  },
  {
    id: 'labord_004',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(3),
    updated_at: daysAgoIso(3),
    customer_id: 'cust_001',
    sale_id: null,
    ordered_by_user_id: 'user_002',
    status: 'pending',
    test_catalog_id: 'test_004',
  },
  {
    id: 'labord_005',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(1),
    updated_at: daysAgoIso(1),
    customer_id: 'cust_002',
    sale_id: null,
    ordered_by_user_id: 'user_003',
    status: 'result_entered',
    test_catalog_id: 'test_005',
  },
  {
    id: 'labord_006',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: nowIso(),
    updated_at: nowIso(),
    customer_id: 'cust_003',
    sale_id: null,
    ordered_by_user_id: 'user_002',
    status: 'unsolved',
    test_catalog_id: 'test_006',
  },
];
