import type { TestCatalogEntry } from '@40labs/types';
import { WORKSPACE_ID, BRANCH_ID, daysAgoIso } from '../constants';

export const initialTestCatalog: TestCatalogEntry[] = [
  {
    id: 'test_001',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(100),
    updated_at: daysAgoIso(100),
    name: 'Malaria Rapid Test (RDT)',
    category: 'Parasitology',
    reference_range: 'Negative',
    price: 5000,
  },
  {
    id: 'test_002',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(100),
    updated_at: daysAgoIso(100),
    name: 'Fasting Blood Glucose',
    category: 'Chemistry',
    reference_range: '70-100 mg/dL',
    price: 5000,
  },
  {
    id: 'test_003',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(100),
    updated_at: daysAgoIso(100),
    name: 'Full Blood Count (CBC)',
    category: 'Hematology',
    reference_range: 'WBC: 4-11, Hb: 12-16 g/dL',
    price: 15000,
  },
  {
    id: 'test_004',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(100),
    updated_at: daysAgoIso(100),
    name: 'Widal Test (Typhoid)',
    category: 'Serology',
    reference_range: '< 1:80',
    price: 8000,
  },
  {
    id: 'test_005',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(100),
    updated_at: daysAgoIso(100),
    name: 'Urinalysis (Dipstick)',
    category: 'Urinalysis',
    reference_range: 'Normal',
    price: 6000,
  },
  {
    id: 'test_006',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(100),
    updated_at: daysAgoIso(100),
    name: 'HIV Rapid Screening Test',
    category: 'Serology',
    reference_range: 'Non-reactive',
    price: 5000,
  },
  {
    id: 'test_007',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(100),
    updated_at: daysAgoIso(100),
    name: 'Stool Routine Examination',
    category: 'Parasitology',
    reference_range: 'No ova or parasites seen',
    price: 7000,
  },
  {
    id: 'test_008',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(100),
    updated_at: daysAgoIso(100),
    name: 'Lipid Profile',
    category: 'Chemistry',
    reference_range: 'Cholesterol: < 200 mg/dL',
    price: 25000,
  },
];
