// [PHASE: MVP]
import type { Customer } from '@40labs/types';
import { WORKSPACE_ID, BRANCH_ID, daysAgoIso } from '../constants';

export const initialCustomers: Customer[] = [
  {
    id: "cust_001",
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(120),
    updated_at: daysAgoIso(3),
    full_name: "Juma Hamisi",
    phone: "+255606113565",
    email: null,
    outstanding_balance: 15000,
    notes: "Regular customer, prefers generics.",
    amob_patient_id: null,
  },
  {
    id: "cust_002",
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(80),
    updated_at: daysAgoIso(12),
    full_name: "Anna Yajilo",
    phone: "+255606113566",
    email: "anna.yajilo@example.com",
    outstanding_balance: 0,
    notes: null,
    amob_patient_id: null,
  },
  {
    id: "cust_003",
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(5),
    updated_at: daysAgoIso(5),
    full_name: "Jane Kimario",
    phone: "+255696571221",
    email: null,
    outstanding_balance: 50000,
    notes: "Debtor — reminded 2026-08-20",
    amob_patient_id: null,
  },
  {
    id: "cust_004",
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(110),
    updated_at: daysAgoIso(2),
    full_name: "Amina Mbarak",
    phone: "+255712345678",
    email: "amina.mbarak@gmail.com",
    outstanding_balance: 0,
    notes: "Prefers brand-name prescription refills.",
    amob_patient_id: null,
  },
  {
    id: "cust_005",
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(95),
    updated_at: daysAgoIso(5),
    full_name: "Baraka Msigwa",
    phone: "+255754987654",
    email: null,
    outstanding_balance: 12500,
    notes: "Monthly chronic medication pickup.",
    amob_patient_id: null,
  },
  {
    id: "cust_006",
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(80),
    updated_at: daysAgoIso(1),
    full_name: "Neema Mwakyusa",
    phone: "+255683112233",
    email: "neema.m@yahoo.com",
    outstanding_balance: 4500,
    notes: "Requested home delivery for bulky items.",
    amob_patient_id: null,
  },
  {
    id: "cust_007",
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(60),
    updated_at: daysAgoIso(10),
    full_name: "Rashid Omari",
    phone: "+255714556677",
    email: null,
    outstanding_balance: 0,
    notes: "Walk-in customer, pays cash.",
    amob_patient_id: null,
  },
  {
    id: "cust_008",
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(45),
    updated_at: daysAgoIso(4),
    full_name: "Zuhura Kassim",
    phone: "+255655223344",
    email: "zuhura.k@outlook.com",
    outstanding_balance: 22000,
    notes: "Corporate insurance client.",
    amob_patient_id: null,
  },
  {
    id: "cust_009",
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(30),
    updated_at: daysAgoIso(2),
    full_name: "Godfrey Mrema",
    phone: "+255767889900",
    email: null,
    outstanding_balance: 8000,
    notes: "Allergic to penicillin, verify all scripts.",
    amob_patient_id: null,
  },
  {
    id: "cust_010",
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(20),
    updated_at: daysAgoIso(6),
    full_name: "Grace Kimaro",
    phone: "+255789123456",
    email: "grace.kimaro@gmail.com",
    outstanding_balance: 0,
    notes: "Buys supplements regularly.",
    amob_patient_id: null,
  },
  {
    id: "cust_011",
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(15),
    updated_at: daysAgoIso(1),
    full_name: "Hassan Juma",
    phone: "+255622334455",
    email: null,
    outstanding_balance: 35000,
    notes: "Pending insurance claim verification.",
    amob_patient_id: null,
  },
  {
    id: "cust_012",
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(10),
    updated_at: daysAgoIso(0),
    full_name: "Rehema Selemani",
    phone: "+255715998877",
    email: "rehema.s@hotmail.com",
    outstanding_balance: 1500,
    notes: "Quick service pickup.",
    amob_patient_id: null,
  },
  {
    id: "cust_013",
    workspace_id: BRANCH_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(5),
    updated_at: daysAgoIso(0),
    full_name: "Emmanuel Mhando",
    phone: "+255673445566",
    email: null,
    outstanding_balance: 0,
    notes: "New customer.",
    amob_patient_id: null,
  },
];
