import type { Notification } from '@40labs/types';
import { WORKSPACE_ID, BRANCH_ID, daysAgoIso } from '../constants';
import { initialSecondBusiness } from '../pharmacies/pharmacies';

export const initialNotifications: Notification[] = [
  {
    id: 'notif_001',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(1),
    updated_at: daysAgoIso(1),
    category: 'customers',
    source_type: 'remote',
    sender_name: 'Glory Njiku',
    sender_business_id: null,
    subject: 'Product Question',
    body: 'Do you have Amoxicillin 500mg in stock?',
    status: 'unread',
    related_entity_type: null,
    related_entity_id: null,
    received_at: daysAgoIso(1),
  },
  {
    id: 'notif_002',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(2),
    updated_at: daysAgoIso(2),
    category: 'gov',
    source_type: 'remote',
    sender_name: 'TMDA',
    sender_business_id: 'AFYA-0001',
    subject: 'Health Org: Annual Regulatory Inspection & Compliance Notice',
    body: 'Notice of upcoming TMDA premises inspection and mandatory fee clearance for Q3 2026.',
    status: 'unread',
    related_entity_type: null,
    related_entity_id: null,
    received_at: daysAgoIso(2),
  },
  {
    id: 'notif_003',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(3),
    updated_at: daysAgoIso(3),
    category: 'customers',
    source_type: 'remote',
    sender_name: 'Anna Mwita',
    sender_business_id: null,
    subject: 'Product Question',
    body: 'Can I order Paracetamol syrup for pickup tomorrow morning?',
    status: 'read',
    related_entity_type: null,
    related_entity_id: null,
    received_at: daysAgoIso(3),
  },
  {
    id: 'notif_004',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(4),
    updated_at: daysAgoIso(4),
    category: 'gov',
    source_type: 'remote',
    sender_name: 'TRA',
    sender_business_id: 'AFYA-0002',
    subject: 'Fin Org: EFD/VFD Fiscal Reconciliation Reminder',
    body: 'Please reconcile all offline queued sales receipts to ensure TRA EFD compliance.',
    status: 'read',
    related_entity_type: 'FiscalReceipt',
    related_entity_id: null,
    received_at: daysAgoIso(4),
  },
  {
    id: 'notif_005',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(5),
    updated_at: daysAgoIso(5),
    category: 'marketing',
    source_type: 'system',
    sender_name: '40Labs',
    sender_business_id: null,
    subject: 'Product updates',
    body: 'Version 2.4 update available: New notifications center and offline sync improvements.',
    status: 'read',
    related_entity_type: null,
    related_entity_id: null,
    received_at: daysAgoIso(5),
  },
  {
    id: 'notif_006',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(6),
    updated_at: daysAgoIso(6),
    category: 'business',
    source_type: 'remote',
    sender_name: 'Emy Pharmacy',
    sender_business_id: initialSecondBusiness.business_id,
    subject: 'Product updates',
    body: 'Shared stock catalog updated for inter-branch wholesale requests.',
    status: 'archived',
    related_entity_type: null,
    related_entity_id: null,
    received_at: daysAgoIso(6),
  },
];
