import type { Notification } from '@40labs/types';
import { WORKSPACE_ID, BRANCH_ID, daysAgoIso } from '../constants';
import { initialSecondBusiness } from '../pharmacies/pharmacies';

export const initialNotifications: Notification[] = [
  {
    id: 'notif_001',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(1),
    updated_at: daysAgoIso(1),
    category: 'customers',
    source_type: 'remote',
    sender_name: 'Glory Njiku',
    sender_business_id: null,
    subject: 'Product Question',
    body: '## Prescription Inquiry\n\nDo you have Amoxicillin 500mg in stock?\n\n- Patient requires 2 packs\n- Pickup scheduled for tomorrow morning\n\n[Check Inventory Portal](https://portal.40labs.io/inventory)',
    status: 'unread',
    channel: 'amob',
    content_type: 'markdown',
    related_entity_type: null,
    related_entity_id: null,
    received_at: daysAgoIso(1),
  },
  {
    id: 'notif_002',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(2),
    updated_at: daysAgoIso(2),
    category: 'gov',
    source_type: 'remote',
    sender_name: 'TMDA',
    sender_business_id: 'AFYA-0001',
    subject: 'Health Org: Annual Regulatory Inspection & Compliance Notice',
    body: 'Notice of upcoming TMDA premises inspection and mandatory fee clearance for Q3 2026.',
    status: 'unread',
    channel: 'email',
    content_type: 'html',
    html_content: '<div style="font-family:sans-serif; padding:8px;"><h3 style="color:#0284c7;">TMDA Official Notice</h3><p>Notice of upcoming <strong>TMDA premises inspection</strong> and mandatory fee clearance for Q3 2026.</p><p><a href="https://tmda.go.tz/portal" target="_blank">View Regulatory Portal</a></p></div>',
    plain_text_content: 'TMDA Official Notice: Notice of upcoming TMDA premises inspection and mandatory fee clearance for Q3 2026. View portal at https://tmda.go.tz/portal',
    attachments: [
      {
        id: 'att_01',
        type: 'file',
        name: 'tmda_inspection_q3_notice.pdf',
        size: '1.4 MB',
        url: 'https://tmda.go.tz/docs/notice.pdf',
      },
    ],
    related_entity_type: null,
    related_entity_id: null,
    received_at: daysAgoIso(2),
  },
  {
    id: 'notif_003',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(3),
    updated_at: daysAgoIso(3),
    category: 'customers',
    source_type: 'remote',
    sender_name: 'Anna Mwita',
    sender_business_id: null,
    subject: 'WhatsApp Order & Photo Prescription',
    body: 'Can I order Paracetamol syrup for pickup tomorrow morning? Here is the prescription photo.',
    status: 'read',
    channel: 'whatsapp',
    content_type: 'image',
    attachments: [
      {
        id: 'att_02',
        type: 'image',
        name: 'prescription_photo.png',
        size: '850 KB',
        url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
      },
      {
        id: 'att_03',
        type: 'audio',
        name: 'voice_note_anna.wav',
        size: '0:24',
      },
    ],
    related_entity_type: null,
    related_entity_id: null,
    received_at: daysAgoIso(3),
  },
  {
    id: 'notif_004',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(4),
    updated_at: daysAgoIso(4),
    category: 'gov',
    source_type: 'remote',
    sender_name: 'TRA',
    sender_business_id: 'AFYA-0002',
    subject: 'Fin Org: EFD/VFD Fiscal Reconciliation Reminder',
    body: 'Please reconcile all offline queued sales receipts to ensure TRA EFD compliance. *Do not ignore*.',
    status: 'read',
    channel: 'sms',
    content_type: 'text',
    related_entity_type: 'FiscalReceipt',
    related_entity_id: null,
    received_at: daysAgoIso(4),
  },
  {
    id: 'notif_005',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(5),
    updated_at: daysAgoIso(5),
    category: 'marketing',
    source_type: 'system',
    sender_name: '40Labs',
    sender_business_id: null,
    subject: 'Product updates',
    body: '## Version 2.4 Release Notes\n\n- Unified message rendering system\n- Markdown & sanitized HTML email support\n- Attachment preview tray & audio player\n\nVisit [40Labs Hub](https://40labs.io)',
    status: 'read',
    channel: 'amob',
    content_type: 'markdown',
    related_entity_type: null,
    related_entity_id: null,
    received_at: daysAgoIso(5),
  },
  {
    id: 'notif_006',
    workspace_id: WORKSPACE_ID,
    branch_id: BRANCH_ID,
    created_at: daysAgoIso(6),
    updated_at: daysAgoIso(6),
    category: 'business',
    source_type: 'remote',
    sender_name: 'Emy Pharmacy',
    sender_business_id: initialSecondBusiness.business_id,
    subject: 'Wholesale Stock Catalog',
    body: 'Shared stock catalog updated for inter-branch wholesale requests.',
    status: 'archived',
    channel: 'sms',
    content_type: 'text',
    related_entity_type: null,
    related_entity_id: null,
    received_at: daysAgoIso(6),
  },
];
