import * as React from 'react';
import {
  Panel,
  Avatar,
  Badge,
  Button,
  IconButton,
  Textarea,
  Tooltip,
} from '@40labs/ui-components';
import {
  Mail,
  Tag,
  CheckCircle2,
  Archive,
  Trash2,
  Send,
  MessageSquare,
} from 'lucide-react';
import type { Notification, NotificationCategory } from '@40labs/types';
import { CAN_REPLY_BY_CATEGORY } from '../replyPolicy';

export interface NotificationDetailPanelProps {
  notification?: Notification | null;
  onMarkAsRead?: (id: string) => void;
  onArchive?: (id: string) => void;
  onDelete?: (id: string) => void;
  onSendReply?: (id: string, replyText: string) => void;
  className?: string;
}

const SENDER_TONES: Array<'primary' | 'accent' | 'danger' | 'neutral'> = [
  'primary',
  'accent',
  'danger',
  'neutral',
];

function getSenderTone(key: string): 'primary' | 'accent' | 'danger' | 'neutral' {
  let hash = 0;
  for (let i = 0; i < key.length; i++) {
    hash = (hash << 5) - hash + key.charCodeAt(i);
    hash |= 0;
  }
  const index = Math.abs(hash) % SENDER_TONES.length;
  return SENDER_TONES[index];
}

const categoryBadgeVariants: Record<
  NotificationCategory,
  'warning' | 'primary' | 'neutral' | 'surface'
> = {
  gov: 'warning',
  customers: 'primary',
  marketing: 'neutral',
  business: 'surface',
};

interface MessageBubble {
  id: string;
  sender: 'incoming' | 'outgoing';
  senderName: string;
  text: string;
  timestamp: string;
}

function formatTime(isoString: string): string {
  try {
    const date = new Date(isoString);
    if (isNaN(date.getTime())) return isoString;
    return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  } catch {
    return isoString;
  }
}

function parseConversationMessages(notification: Notification): MessageBubble[] {
  const messages: MessageBubble[] = [];
  const rawBody = notification.body || '';
  const initialTime = formatTime(notification.received_at || notification.created_at);

  // Split by reply separator generated by useNotifications: "\n\n--- You replied (...) ---\n"
  const parts = rawBody.split(/--- You replied \((.*?)\) ---/);

  const initialText = parts[0]?.trim() || notification.subject;
  messages.push({
    id: `${notification.id}-initial`,
    sender: 'incoming',
    senderName: notification.sender_name,
    text: initialText,
    timestamp: initialTime,
  });

  for (let i = 1; i < parts.length; i += 2) {
    const timeLabel = parts[i] || 'Just now';
    const replyText = parts[i + 1]?.trim() || '';
    if (replyText) {
      messages.push({
        id: `${notification.id}-reply-${i}`,
        sender: 'outgoing',
        senderName: 'You',
        text: replyText,
        timestamp: timeLabel,
      });
    }
  }

  return messages;
}

export const NotificationDetailPanel: React.FC<NotificationDetailPanelProps> = ({
  notification,
  onMarkAsRead,
  onArchive,
  onDelete,
  onSendReply,
  className = '',
}) => {
  const [replyText, setReplyText] = React.useState('');
  const messagesEndRef = React.useRef<HTMLDivElement>(null);

  // Clear unsent reply text whenever notification selection changes
  React.useEffect(() => {
    setReplyText('');
  }, [notification?.id]);

  // Scroll to bottom of message thread on new message or selection
  React.useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [notification?.body, notification?.id]);

  if (!notification) {
    return (
      <div className={`w-full h-full flex flex-col items-center justify-center bg-panel border border-border/40 rounded-card p-8 text-center ${className}`}>
        <Panel variant="flat" className="p-8 max-w-sm mx-auto flex flex-col items-center gap-3 bg-panel-strong/30 border border-border/30 rounded-card">
          <div className="w-12 h-12 rounded-full bg-panel-strong flex items-center justify-center text-text-muted">
            <Mail size={24} />
          </div>
          <h3 className="text-sm font-bold text-text">No Conversation Selected</h3>
          <p className="text-xs text-text-muted">
            Select a conversation from the inbox list to view the message thread and reply.
          </p>
        </Panel>
      </div>
    );
  }

  const senderKey = notification.sender_business_id ?? notification.sender_name;
  const tone = getSenderTone(senderKey);
  const canReply = CAN_REPLY_BY_CATEGORY[notification.category] ?? false;
  const messages = parseConversationMessages(notification);

  const handleSendReply = () => {
    if (!replyText.trim() || !notification) return;
    onSendReply?.(notification.id, replyText.trim());
    setReplyText('');
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) {
      e.preventDefault();
      handleSendReply();
    }
  };

  return (
    <div className={`w-full h-full flex flex-col bg-panel border border-border/40 rounded-card overflow-hidden shadow-xs ${className}`}>
      {/* Compact Conversation Header */}
      <div className="bg-panel-strong/50 flex flex-col gap-2 p-3.5 border-b border-border/30 shrink-0">
        <div className="flex items-center justify-between gap-2">
          <div className="flex items-center gap-2.5">
            <Avatar name={notification.sender_name} tone={tone} size="md" />
            <div className="flex flex-col min-w-0">
              <div className="flex items-center gap-2">
                <h2 className="text-xs font-bold text-text truncate">
                  {notification.sender_name}
                </h2>
                {notification.sender_business_id && (
                  <span className="text-[10px] text-text-muted font-mono hidden sm:inline">
                    ({notification.sender_business_id})
                  </span>
                )}
              </div>
              <span className="text-[10px] text-text-muted flex items-center gap-1 font-mono">
                <MessageSquare size={11} /> {notification.source_type} channel
              </span>
            </div>
          </div>

          <div className="flex items-center gap-2 shrink-0">
            <Badge variant={categoryBadgeVariants[notification.category] || 'neutral'} size="sm">
              {notification.category}
            </Badge>

            <div className="flex items-center gap-1">
              {onMarkAsRead && notification.status === 'unread' && (
                <Tooltip content="Mark as read">
                  <Button
                    type="button"
                    intent="neutral"
                    size="sm"
                    onClick={() => onMarkAsRead(notification.id)}
                    className="h-7 text-[11px] px-2"
                    leftIcon={<CheckCircle2 size={12} />}
                  >
                    Read
                  </Button>
                </Tooltip>
              )}
              {onArchive && notification.status !== 'archived' && (
                <Tooltip content="Archive conversation">
                  <Button
                    type="button"
                    intent="neutral"
                    size="sm"
                    onClick={() => onArchive(notification.id)}
                    className="h-7 text-[11px] px-2"
                    leftIcon={<Archive size={12} />}
                  >
                    Archive
                  </Button>
                </Tooltip>
              )}
              {onDelete && (
                <Tooltip content="Delete conversation">
                  <IconButton
                    icon={<Trash2 size={13} />}
                    label="Delete"
                    intent="ghost"
                    size="sm"
                    onClick={() => onDelete(notification.id)}
                    className="text-danger hover:bg-danger/10"
                  />
                </Tooltip>
              )}
            </div>
          </div>
        </div>

        {/* Conversation Subject Context Bar */}
        <div className="flex items-center justify-between gap-2 px-3 py-1.5 bg-panel-strong/30 border border-border/20 rounded-input">
          <span className="text-xs font-semibold text-text truncate">
            Subject: {notification.subject}
          </span>
          <span className="text-[10px] text-text-muted font-mono shrink-0">
            {new Date(notification.received_at || notification.created_at).toLocaleDateString([], {
              month: 'short',
              day: 'numeric',
            })}
          </span>
        </div>
      </div>

      {/* Continuous Message Thread Workspace (Primary Focus) */}
      <div className="flex-1 overflow-y-auto p-4 custom-scrollbar flex flex-col gap-4">
        {messages.map((msg) => {
          const isOutgoing = msg.sender === 'outgoing';
          return (
            <div
              key={msg.id}
              className={`flex flex-col gap-1 max-w-[85%] ${
                isOutgoing ? 'ml-auto items-end' : 'mr-auto items-start'
              }`}
            >
              <div className="flex items-center gap-1.5 px-1">
                <span className="text-[10px] font-bold text-text-muted">
                  {msg.senderName}
                </span>
                <span className="text-[10px] text-text-muted">•</span>
                <span className="text-[10px] font-mono text-text-muted">{msg.timestamp}</span>
              </div>

              <div
                className={`p-3.5 rounded-2xl text-xs leading-relaxed whitespace-pre-wrap font-ui shadow-2xs ${
                  isOutgoing
                    ? 'bg-primary/15 text-text border border-primary/30 rounded-tr-sm'
                    : 'bg-panel-strong/60 text-text border border-border/30 rounded-tl-sm'
                }`}
              >
                {msg.text}
              </div>
            </div>
          );
        })}

        {/* Related Entity Reference */}
        {notification.related_entity_type && (
          <div className="my-2">
            <Panel
              variant="flat"
              className="p-2.5 bg-panel-strong/30 border border-border/30 rounded-card flex items-center justify-between text-xs shrink-0"
            >
              <div className="flex items-center gap-2 text-text-muted">
                <Tag size={13} />
                <span>
                  Related Entity: <strong className="text-text">{notification.related_entity_type}</strong>
                </span>
                {notification.related_entity_id && (
                  <span className="font-mono text-[11px]">({notification.related_entity_id})</span>
                )}
              </div>
            </Panel>
          </div>
        )}

        <div ref={messagesEndRef} />
      </div>

      {/* Reply Composer at bottom */}
      <div className="p-3 bg-panel-strong/30 border-t border-border/30 shrink-0">
        {canReply ? (
          <div className="flex items-end gap-2 bg-panel p-2 rounded-card border border-border/40 shadow-2xs">
            <Textarea
              value={replyText}
              onChange={(e) => setReplyText(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder="Write a reply... (Ctrl+Enter to send)"
              className="flex-1 text-xs min-h-[50px] max-h-[110px] resize-none border-0 bg-transparent p-1 focus:ring-0 shadow-none"
            />
            <IconButton
              icon={<Send size={15} />}
              label="Send Reply"
              intent="primary"
              size="md"
              disabled={!replyText.trim()}
              onClick={handleSendReply}
              className="shrink-0 rounded-full"
            />
          </div>
        ) : (
          <p className="text-xs text-text-muted italic text-center py-1.5">
            This sender channel does not accept replies in-app.
          </p>
        )}
      </div>
    </div>
  );
};
